version: '3.2'
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports: 
      - "3308:3306"

  app:
    image: cds-fhir-server
    build:
      context: .
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cdss_resources?useSSL=false
    ports: 
      - "8084:8084"
    restart: on-failure:5