package uk.nhs.cdss.resourceProviders;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.hl7.fhir.dstu3.model.*;

@AllArgsConstructor
@Getter
public enum SupportedResources {

  BUNDLE(Bundle .class),
  PARAMETERS(Parameters .class),
  DEVICEREQUEST(DeviceRequest .class),
  MEDICATIONADMINISTRATION(MedicationAdministration .class),
  EPISODEOFCARE(EpisodeOfCare .class),
  ENROLLMENTREQUEST(EnrollmentRequest .class),
  LISTRESOURCE(ListResource .class),
  LINKAGE(Linkage .class),
  AUDITEVENT(AuditEvent .class),
  ORGANIZATION(Organization .class),
  SCHEDULE(Schedule .class),
  DIAGNOSTICREPORT(DiagnosticReport .class),
  MEDICATION(Medication .class),
  ELIGIBILITYRESPONSE(EligibilityResponse .class),
  QUESTIONNAIRERESPONSE(QuestionnaireResponse .class),
  MEASUREREPORT(MeasureReport .class),
  IMAGINGMANIFEST(ImagingManifest .class),
  DOCUMENTMANIFEST(DocumentManifest .class),
  OPERATIONOUTCOME(OperationOutcome.class),
  ACCOUNT(Account .class),
  DEVICEMETRIC(DeviceMetric .class),
  COVERAGE(Coverage .class),
  EXPLANATIONOFBENEFIT(ExplanationOfBenefit .class),
  CONTRACT(Contract.class),
  IMAGINGSTUDY(ImagingStudy .class),
  RELATEDPERSON(RelatedPerson .class),
  DOCUMENTREFERENCE(DocumentReference .class),
  RESEARCHSTUDY(ResearchStudy .class),
  MEDIA(Media.class),
  COMMUNICATION(Communication .class),
  SUPPLYREQUEST(SupplyRequest .class),
  APPOINTMENT(Appointment .class),
  APPOINTMENTRESPONSE(AppointmentResponse .class),
  PROCEDURE(Procedure.class),
  ENCOUNTER(Encounter .class),
  CLAIMRESPONSE(ClaimResponse .class),
  CAREPLAN(CarePlan.class),
  PROVENANCE(Provenance .class),
  RISKASSESSMENT(RiskAssessment .class),
  SUBSTANCE(Substance .class),
  ENDPOINT(Endpoint.class),
  FAMILYMEMBERHISTORY(FamilyMemberHistory .class),
  COMPOSITION(Composition .class),
  SPECIMEN(Specimen .class),
  FLAG(Flag.class),
  CARETEAM(CareTeam .class),
  DEVICE(Device .class),
  RESEARCHSUBJECT(ResearchSubject .class),
  MEDICATIONREQUEST(MedicationRequest .class),
  ENROLLMENTRESPONSE(EnrollmentResponse .class),
  SLOT(org.hl7.fhir.dstu3.model.Slot.class),
  CLAIM(Claim .class),
  SUBSCRIPTION(Subscription.class),
  REFERRALREQUEST(ReferralRequest .class),
  ADVERSEEVENT(AdverseEvent .class),
  ELIGIBILITYREQUEST(EligibilityRequest .class),
  PROCESSREQUEST(ProcessRequest .class),
  IMMUNIZATION(Immunization .class),
  CLINICALIMPRESSION(ClinicalImpression .class),
  DETECTEDISSUE(DetectedIssue .class),
  GROUP(org.hl7.fhir.dstu3.model.Group.class),
  MESSAGEHEADER(MessageHeader .class),
  PAYMENTNOTICE(PaymentNotice .class),
  REQUESTGROUP(RequestGroup .class),
  TASK(Task.class),
  MEDICATIONSTATEMENT(MedicationStatement .class),
  SUPPLYDELIVERY(SupplyDelivery .class),
  BODYSITE(BodySite .class),
  LOCATION(Location.class),
  CHARGEITEM(ChargeItem .class),
  IMMUNIZATIONRECOMMENDATION(ImmunizationRecommendation .class),
  PRACTITIONER(Practitioner .class),
  HEALTHCARESERVICE(HealthcareService .class),
  GOAL(Goal .class),
  ALLERGYINTOLERANCE(AllergyIntolerance .class),
  DEVICECOMPONENT(DeviceComponent .class),
  CONSENT(Consent .class),
  DEVICEUSESTATEMENT(DeviceUseStatement .class),
  PAYMENTRECONCILIATION(PaymentReconciliation .class),
  CONDITION(Condition.class),
  VISIONPRESCRIPTION(VisionPrescription .class),
  OBSERVATION(Observation .class),
  TESTREPORT(TestReport .class),
  GUIDANCERESPONSE(GuidanceResponse .class),
  SEQUENCE(Sequence.class),
  BASIC(Basic.class),
  PATIENT(Patient.class),
  COMMUNICATIONREQUEST(CommunicationRequest .class),
  PROCEDUREREQUEST(ProcedureRequest .class),
  PROCESSRESPONSE(ProcessResponse .class),
  MEDICATIONDISPENSE(MedicationDispense .class),
  PERSON(Person .class),
  PRACTITIONERROLE(PractitionerRole.class),
  NUTRITIONORDER(NutritionOrder .class),
  ACTIVITYDEFINITION(ActivityDefinition .class),
  DATAELEMENT(DataElement .class),
  NAMINGSYSTEM(NamingSystem .class),
  IMPLEMENTATIONGUIDE(ImplementationGuide .class),
  GRAPHDEFINITION(GraphDefinition .class),
  MEASURE(Measure .class),
  SEARCHPARAMETER(SearchParameter.class),
  COMPARTMENTDEFINITION(CompartmentDefinition .class),
  MESSAGEDEFINITION(MessageDefinition .class),
  CODESYSTEM(CodeSystem .class),
  STRUCTUREMAP(StructureMap .class),
  SERVICEDEFINITION(ServiceDefinition .class),
  CAPABILITYSTATEMENT(CapabilityStatement .class),
  QUESTIONNAIRE(Questionnaire .class),
  PLANDEFINITION(PlanDefinition .class),
  OPERATIONDEFINITION(OperationDefinition .class),
  STRUCTUREDEFINITION(StructureDefinition .class),
  LIBRARY(Library.class),
  CONCEPTMAP(ConceptMap .class),
  EXPANSIONPROFILE(ExpansionProfile .class),
  VALUESET(ValueSet .class),
  TESTSCRIPT(TestScript .class),

  /** CUSTOM RESOURCES **/
  COORDINATES(CoordinateResource.class);


  private Class<? extends Resource> resourceClass;


}
